### ISSUE TITLE
Provide Compiled Versions

### ISSUE THREAD

**Issue by J-T-de** [CIO61/aic_gui#1]
Very nice work,

I think it would be really helpful to provide compiled (Windows-) versions of this program. Because currently, the threshold to run this program might be too high for the wider Audience:

- download and install python (this is okay I think)
- install PyQt5 and regex (at least my CPyhon version is not shipped with those, and using the command line to install those is a huge barrier for many users)

**Comment by CIO61** [comment]
Hello, under [releases page](https://github.com/CIO61/aic_gui/releases), you can find compiled versions of this program. Although it is only available for windows platform, i might add _at least an installer_ for other platforms.

**Comment by J-T-de** [comment]
The new github-layout is killing me, sorry...

**Comment by CIO61** [comment]
Same here
